name: Maven Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'NOTICE'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'NOTICE'
      - 'docs/**'
  release:
    types: [ created ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Tests run
        run: mvn clean install -Pfull-validation jacoco:report checkstyle:checkstyle spotbugs:spotbugs surefire-report:report -B

      - name: Upload spotbugs report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spotbugs-report
          path: target/spotbugs.html

      - name: Upload PMD reports artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pmd-report
          path: target/pmd

      - name: Upload PMD reports html artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html-pmd-report
          path: target/site

      - name: Upload jacoco report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: target/jacoco-report

      - name: Upload tests report artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests-report
          path: target/reports

  publish:
    needs: tests
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          server-id: central

      - name: Install GPG
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg

      - name: Import GPG Key
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish to Maven Central
        run: mvn clean deploy -DserverId=central -DcentralServerId=central -Dgpg.executable=gpg -Dgpg.passphrase=$GPG_PASSPHRASE -DskipTests -P release -B
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USR }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PSW }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}